services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: multi_domain_server:latest
    container_name: multi_domain_server
    command: "uv run -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
    networks:
      - multi_domain_tier

  db:
    image: mongo:8
    restart: unless-stopped
    container_name: multi_domain_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - multi_domain_db:/data/db
    networks:
      - multi_domain_tier

volumes:
  multi_domain_db:
    external: true
    name: multi_domain_db

networks:
  multi_domain_tier:
    driver: bridge


# docker volume create multi_domain_db
